#!/usr/bin/env bash
# Input: this repository plus installed claude/codex/grok/python3 CLIs. Output: user-scoped Claude router install.
# Pos: idempotent macOS/Linux installer for claude-multiengine-router.

set -euo pipefail

PROJECT_NAME="claude-multiengine-router"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

info() {
  printf '[%s] %s\n' "$PROJECT_NAME" "$*"
}

warn() {
  printf '[%s] WARNING: %s\n' "$PROJECT_NAME" "$*" >&2
}

die() {
  printf '[%s] ERROR: %s\n' "$PROJECT_NAME" "$*" >&2
  exit 1
}

detect_os() {
  case "$(uname -s)" in
    Darwin|Linux)
      ;;
    MINGW*|MSYS*|CYGWIN*|Windows_NT)
      die "Windows native install is planned for Phase 2. For Phase 1, use WSL."
      ;;
    *)
      die "Unsupported OS: $(uname -s). Phase 1 supports macOS and Linux only."
      ;;
  esac
}

expand_path() {
  local raw="$1"
  case "$raw" in
    "~")
      printf '%s\n' "$HOME"
      ;;
    "~/"*)
      printf '%s/%s\n' "$HOME" "${raw#~/}"
      ;;
    /*)
      printf '%s\n' "$raw"
      ;;
    *)
      printf '%s/%s\n' "$PWD" "$raw"
      ;;
  esac
}

resolve_cli() {
  local env_name="$1"
  local command_name="$2"
  local install_hint="$3"
  local configured="${!env_name:-}"

  if [[ -n "$configured" ]]; then
    configured="$(expand_path "$configured")"
    [[ -x "$configured" ]] || die "$env_name is set but not executable: $configured. $install_hint"
    printf '%s\n' "$configured"
    return
  fi

  local found
  found="$(command -v "$command_name" || true)"
  [[ -n "$found" ]] || die "Missing required CLI: $command_name. $install_hint"
  printf '%s\n' "$found"
}

sed_escape() {
  printf '%s' "$1" | sed -e 's/[\/&|]/\\&/g'
}

render_template() {
  local src="$1"
  local dest="$2"
  local code_model_flag="$CODEX_MODEL_FLAG"
  sed \
    -e "s|__CODEX_BIN__|$(sed_escape "$CODEX_BIN")|g" \
    -e "s|__GROK_BIN__|$(sed_escape "$GROK_BIN")|g" \
    -e "s|__OUTPUT_DIR__|$(sed_escape "$OUTPUT_DIR")|g" \
    -e "s|__ENABLE_WIKI_LOG__|$(sed_escape "$ENABLE_WIKI_LOG")|g" \
    -e "s|__CODEX_MODEL__|$(sed_escape "$CODEX_MODEL")|g" \
    -e "s|__CODEX_MODEL_FLAG__|$(sed_escape "$code_model_flag")|g" \
    -e "s|__CODEX_MODEL_LABEL__|$(sed_escape "$CODEX_MODEL_LABEL")|g" \
    -e "s|__GROK_MODEL__|$(sed_escape "$GROK_MODEL")|g" \
    "$src" >"$dest"
}

is_managed_path() {
  local target="$1"
  if [[ -f "$target" ]]; then
    grep -q "installed_by: $PROJECT_NAME" "$target" 2>/dev/null
    return
  fi
  if [[ -f "$target/SKILL.md" ]]; then
    grep -q "installed_by: $PROJECT_NAME" "$target/SKILL.md" 2>/dev/null
    return
  fi
  if [[ -f "$target/server.py" ]]; then
    grep -q "$PROJECT_NAME" "$target/server.py" 2>/dev/null
    return
  fi
  return 1
}

backup_unmanaged_if_needed() {
  local target="$1"
  [[ -e "$target" ]] || return 0

  if is_managed_path "$target"; then
    return 0
  fi

  local backup="${target}.bak.${TIMESTAMP}"
  info "Backing up existing $target -> $backup"
  mv "$target" "$backup"
}

check_codex_auth() {
  [[ "${AGENT_ROUTER_SKIP_AUTH_CHECK:-0}" == "1" ]] && return 0
  if "$CODEX_BIN" login status >/tmp/agent-router-codex-login.$$.log 2>&1; then
    rm -f /tmp/agent-router-codex-login.$$.log
    return 0
  fi

  local output
  output="$(cat /tmp/agent-router-codex-login.$$.log 2>/dev/null || true)"
  rm -f /tmp/agent-router-codex-login.$$.log
  die "Codex is installed but not authenticated. Run \`codex login\` first. Last output: ${output:-<empty>}"
}

check_grok_auth() {
  [[ "${AGENT_ROUTER_SKIP_AUTH_CHECK:-0}" == "1" ]] && return 0
  if "$GROK_BIN" models >/tmp/agent-router-grok-models.$$.log 2>&1; then
    rm -f /tmp/agent-router-grok-models.$$.log
    return 0
  fi

  local output
  output="$(cat /tmp/agent-router-grok-models.$$.log 2>/dev/null || true)"
  rm -f /tmp/agent-router-grok-models.$$.log
  die "Grok Build is installed but not authenticated. Run \`grok login\` first. Last output: ${output:-<empty>}"
}

write_runtime_config() {
  local config_dir="$CLAUDE_HOME/agent-router"
  mkdir -p "$config_dir"
  {
    printf '# Generated by claude-multiengine-router install.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf 'export OUTPUT_DIR=%q\n' "$OUTPUT_DIR"
    printf 'export ENABLE_WIKI_LOG=%q\n' "$ENABLE_WIKI_LOG"
    printf 'export CODEX_MODEL=%q\n' "$CODEX_MODEL"
    printf 'export GROK_MODEL=%q\n' "$GROK_MODEL"
    printf 'export CODEX_BIN=%q\n' "$CODEX_BIN"
    printf 'export GROK_BIN=%q\n' "$GROK_BIN"
  } >"$config_dir/config.sh"
}

install_router_files() {
  local skill_target="$CLAUDE_HOME/skills/agent-router"
  backup_unmanaged_if_needed "$skill_target"
  mkdir -p "$skill_target"
  render_template "$REPO_ROOT/skills/agent-router/SKILL.md" "$skill_target/SKILL.md"

  mkdir -p "$CLAUDE_HOME/agents"
  local agent
  for agent in codex-exec codex-fast codex-image codex-review grok-research grok-coder; do
    backup_unmanaged_if_needed "$CLAUDE_HOME/agents/$agent.md"
    render_template "$REPO_ROOT/agents/$agent.md" "$CLAUDE_HOME/agents/$agent.md"
  done

  local mcp_target="$CLAUDE_HOME/mcp-servers/grok-mcp"
  backup_unmanaged_if_needed "$mcp_target"
  mkdir -p "$mcp_target"
  cp "$REPO_ROOT/mcp-servers/grok-mcp/server.py" "$mcp_target/server.py"
  cp "$REPO_ROOT/mcp-servers/grok-mcp/test_server.py" "$mcp_target/test_server.py"
  cp "$REPO_ROOT/mcp-servers/grok-mcp/selftest_stdio.py" "$mcp_target/selftest_stdio.py"
  cp "$REPO_ROOT/mcp-servers/grok-mcp/requirements.txt" "$mcp_target/requirements.txt"

  write_runtime_config
}

install_grok_venv() {
  [[ "${AGENT_ROUTER_SKIP_VENV:-0}" == "1" ]] && {
    warn "Skipping Grok MCP venv install because AGENT_ROUTER_SKIP_VENV=1."
    return 0
  }

  local mcp_target="$CLAUDE_HOME/mcp-servers/grok-mcp"
  "$PYTHON_BIN" -m venv "$mcp_target/.venv"
  "$mcp_target/.venv/bin/python" -m pip install --upgrade pip
  "$mcp_target/.venv/bin/python" -m pip install -r "$mcp_target/requirements.txt"
}

register_mcp_servers() {
  [[ "${AGENT_ROUTER_SKIP_MCP_ADD:-0}" == "1" ]] && {
    warn "Skipping Claude MCP registration because AGENT_ROUTER_SKIP_MCP_ADD=1."
    return 0
  }

  local mcp_target="$CLAUDE_HOME/mcp-servers/grok-mcp"
  local venv_python="$mcp_target/.venv/bin/python"
  [[ -x "$venv_python" ]] || die "Missing venv Python: $venv_python"

  "$CLAUDE_BIN" mcp remove -s user codex >/dev/null 2>&1 || true
  "$CLAUDE_BIN" mcp remove -s user grok >/dev/null 2>&1 || true

  "$CLAUDE_BIN" mcp add -s user codex -- "$CODEX_BIN" mcp-server
  "$CLAUDE_BIN" mcp add -s user grok \
    -e "GROK_BIN=$GROK_BIN" \
    -e "GROK_MODEL=$GROK_MODEL" \
    -- "$venv_python" "$mcp_target/server.py"

  local list_output
  list_output="$("$CLAUDE_BIN" mcp list 2>&1 || true)"
  printf '%s\n' "$list_output"

  printf '%s\n' "$list_output" | grep -Ei 'codex.*connected' >/dev/null || die "Claude MCP list did not show codex as Connected."
  printf '%s\n' "$list_output" | grep -Ei 'grok.*connected' >/dev/null || die "Claude MCP list did not show grok as Connected."
}

main() {
  detect_os

  local config_file="${CONFIG_FILE:-$REPO_ROOT/config.local.sh}"
  if [[ -f "$config_file" ]]; then
    info "Loading config: $config_file"
    # shellcheck disable=SC1090
    source "$config_file"
  fi

  : "${OUTPUT_DIR:="$HOME/.agent-router/output"}"
  : "${ENABLE_WIKI_LOG:=false}"
  : "${CODEX_MODEL:=}"
  : "${GROK_MODEL:=grok-build}"

  OUTPUT_DIR="$(expand_path "$OUTPUT_DIR")"
  ENABLE_WIKI_LOG="$(printf '%s' "$ENABLE_WIKI_LOG" | tr '[:upper:]' '[:lower:]')"
  [[ "$ENABLE_WIKI_LOG" == "true" || "$ENABLE_WIKI_LOG" == "false" ]] || die "ENABLE_WIKI_LOG must be true or false."

  CLAUDE_BIN="$(resolve_cli CLAUDE_BIN claude 'Install Claude Code: https://code.claude.com/docs/en/setup')"
  CODEX_BIN="$(resolve_cli CODEX_BIN codex 'Install Codex CLI: https://developers.openai.com/codex/cli')"
  GROK_BIN="$(resolve_cli GROK_BIN grok 'Install Grok Build: https://docs.x.ai/build/overview')"
  PYTHON_BIN="$(resolve_cli PYTHON_BIN python3 'Install Python 3: https://www.python.org/downloads/')"

  if [[ -n "$CODEX_MODEL" ]]; then
    CODEX_MODEL_FLAG="-m \"$CODEX_MODEL\""
    CODEX_MODEL_LABEL="$CODEX_MODEL"
  else
    CODEX_MODEL_FLAG=""
    CODEX_MODEL_LABEL="Codex config default"
  fi

  CLAUDE_HOME="${CLAUDE_HOME:-$HOME/.claude}"

  info "Checking authentication."
  check_codex_auth
  check_grok_auth

  info "Installing router files into $CLAUDE_HOME."
  install_router_files

  info "Installing Grok MCP Python environment."
  install_grok_venv

  info "Registering Claude MCP servers."
  register_mcp_servers

  info "Install complete."
  printf '\nUsage:\n'
  printf '  1. Restart Claude Code if it was already running.\n'
  printf '  2. Ask Claude to use the agent-router skill for multi-engine delegation.\n'
  printf '  3. Available agents: codex-exec, codex-fast, codex-image, codex-review, grok-research, grok-coder.\n'
  printf '\nRisk reminder: Codex execution uses danger-full-access. Only delegate tasks after understanding the local filesystem and network risk.\n'
}

main "$@"
